/*
 * Copyright (c) 2026, Andreas Kling <andreas@ladybird.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Bytecode instruction types generated from Bytecode.def.
//!
//! The `OpCode` enum, `Instruction` enum, and all encoding/visiting methods
//! are generated by build.rs from the same Bytecode.def file that the C++
//! code generator uses. This ensures the Rust types stay in sync with C++.

include!(concat!(env!("OUT_DIR"), "/instruction_generated.rs"));
