/*
 * Copyright (c) 2026, Andreas Kling <andreas@ladybird.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Bytecode generator infrastructure for the Rust parser.
//!
//! This module contains the types and machinery needed to generate
//! bytecode from the Rust AST. The generated bytecode is binary-
//! compatible with the `Bytecode::Executable` format.

pub mod basic_block;
pub mod codegen;
pub mod ffi;
pub mod generator;
pub mod instruction;
pub mod operand;
