#!/usr/bin/env python3

# Copyright (c) 2022-2026, Sam Atkins <sam@ladybird.org>
# Copyright (c) 2026-present, the Ladybird developers.
#
# SPDX-License-Identifier: BSD-2-Clause

import argparse
import json
import sys

from pathlib import Path
from typing import TextIO

sys.path.append(str(Path(__file__).resolve().parent.parent))

from Utils.utils import title_casify


def write_header_file(out: TextIO, functions_data: dict) -> None:
    out.write("""
// This file is generated by GenerateCSSMathFunctions.cpp

#pragma once

#include <AK/Optional.h>
#include <AK/StringView.h>

namespace Web::CSS {

enum class MathFunction {
    Calc,
""")

    for name in functions_data:
        out.write(f"    {title_casify(name)},\n")

    out.write("""
};

Optional<MathFunction> math_function_from_string(StringView);
""")
    out.write("    \n")
    out.write("""}
""")


def write_implementation_file(out: TextIO, functions_data: dict) -> None:
    out.write("""
// This file is generated by GenerateCSSMathFunctions.cpp

#include <LibWeb/CSS/MathFunctions.h>

namespace Web::CSS {

Optional<MathFunction> math_function_from_string(StringView name)
{
    if (name.equals_ignoring_ascii_case("calc"sv))
        return MathFunction::Calc;
""")

    for name in functions_data:
        out.write(f"""
    if (name.equals_ignoring_ascii_case("{name}"sv))
        return MathFunction::{title_casify(name)};
""")

    out.write("""
    return {};
}

}
""")


def main():
    parser = argparse.ArgumentParser(description="Generate CSS MathFunctions", add_help=False)
    parser.add_argument("--help", action="help", help="Show this help message and exit")
    parser.add_argument("-h", "--header", required=True, help="Path to the MathFunctions header file to generate")
    parser.add_argument(
        "-c",
        "--implementation",
        required=True,
        help="Path to the MathFunctions implementation file to generate",
    )
    parser.add_argument("-j", "--json", required=True, help="Path to the JSON file to read from")
    args = parser.parse_args()

    with open(args.json, "r", encoding="utf-8") as input_file:
        functions_data = json.load(input_file)

    with open(args.header, "w", encoding="utf-8") as output_file:
        write_header_file(output_file, functions_data)

    with open(args.implementation, "w", encoding="utf-8") as output_file:
        write_implementation_file(output_file, functions_data)


if __name__ == "__main__":
    main()
