#!/usr/bin/env python3

# Copyright (c) 2026-present, the Ladybird developers.
#
# SPDX-License-Identifier: BSD-2-Clause

import argparse
import json

PARAMETER_TYPE_NAMES = {
    "angle": "Angle",
    "length": "Length",
    "length-none": "LengthNone",
    "length-percentage": "LengthPercentage",
    "number": "Number",
    "number-percentage": "NumberPercentage",
}


def title_casify_transform_function(name: str) -> str:
    # Transform function names look like `fooBar`, so we just have to make the first character uppercase.
    return name[0].upper() + name[1:]


def write_generated_file(transforms_data: dict, output_path: str) -> None:
    with open(output_path, "w", encoding="utf-8") as output_file:
        output_file.write(
            """/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

// Automatically generated by Meta/Generators/generate_libweb_css_transform_functions_rust.py.
// Do not edit.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub(crate) enum TransformFunction {
"""
        )
        for name in transforms_data:
            output_file.write(f"    {title_casify_transform_function(name)},\n")
        output_file.write(
            """}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub(crate) enum TransformFunctionParameterType {
    Angle,
    Length,
    LengthNone,
    LengthPercentage,
    Number,
    NumberPercentage,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct TransformFunctionParameter {
    pub(crate) parameter_type: TransformFunctionParameterType,
    pub(crate) required: bool,
}

"""
        )

        for name, value in transforms_data.items():
            constant_name = name.upper()
            output_file.write(f"const {constant_name}_PARAMETERS: &[TransformFunctionParameter] = &[\n")
            for parameter in value["parameters"]:
                parameter_type_name = parameter["type"].strip("<>")
                if parameter_type_name not in PARAMETER_TYPE_NAMES:
                    raise ValueError(f"Unknown transform function parameter type: {parameter_type_name}")
                parameter_type = PARAMETER_TYPE_NAMES[parameter_type_name]
                required = "true" if parameter["required"] else "false"
                output_file.write(
                    f"    TransformFunctionParameter {{ parameter_type: TransformFunctionParameterType::{parameter_type}, required: {required} }},\n"
                )
            output_file.write("];\n\n")

        output_file.write(
            """pub(crate) fn transform_function_from_name(name: &str) -> Option<TransformFunction> {
"""
        )
        for name in transforms_data:
            output_file.write(f"""    if name.eq_ignore_ascii_case("{name}") {{
        return Some(TransformFunction::{title_casify_transform_function(name)});
    }}
""")
        output_file.write(
            """
    None
}

pub(crate) fn transform_function_parameters(function: TransformFunction) -> &'static [TransformFunctionParameter] {
    match function {
"""
        )
        for name in transforms_data:
            output_file.write(
                f"        TransformFunction::{title_casify_transform_function(name)} => {name.upper()}_PARAMETERS,\n"
            )
        output_file.write(
            """    }
}

pub(crate) fn transform_function_parameters_from_name(name: &str) -> Option<&'static [TransformFunctionParameter]> {
    transform_function_from_name(name).map(transform_function_parameters)
}
"""
        )


def main():
    parser = argparse.ArgumentParser(description="Generate Rust CSS transform function metadata", add_help=False)
    parser.add_argument("--help", action="help", help="Show this help message and exit")
    parser.add_argument("-j", "--json", required=True, help="Path to the JSON file to read from")
    parser.add_argument("-o", "--output", required=True, help="Path to the Rust file to generate")
    args = parser.parse_args()

    with open(args.json, "r", encoding="utf-8") as input_file:
        transforms_data = json.load(input_file)

    write_generated_file(transforms_data, args.output)


if __name__ == "__main__":
    main()
