language = "C++"
header = """/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */"""
pragma_once = true
include_version = true
namespaces = ["Web", "CSS", "Parser", "FFI"]
line_length  = 120
tab_width = 4
no_includes = true
sys_includes = ["stdint.h", "stddef.h"]
usize_is_size_t = true

[parse]
parse_deps = false

[parse.expand]
all_features = false

[export]
include = [
    "CssAnchorNameOrScopeValueKind",
    "CssAnimationNameItemKind",
    "CssAnimationNameValueKind",
    "CssBooleanExpressionEventKind",
    "CssCalculationNodeKind",
    "CssColorSchemeValue",
    "CssColorSchemeValueKind",
    "CssColorValueKind",
    "CssComponentValue",
    "CssComponentValueKind",
    "CssContainValue",
    "CssContainValueKind",
    "CssContainerTypeValueKind",
    "CssCounterStyleKind",
    "CssCounterStyleNegativeSymbolCount",
    "CssCounterStyleRangeKind",
    "CssCounterStyleSymbolsType",
    "CssCounterStyleSystemKind",
    "CssCropOrCrossKind",
    "CssDeclaration",
    "CssDescriptorResultKind",
    "CssDescriptorSyntaxKind",
    "CssDescriptorValueType",
    "CssFontFamilyValueKind",
    "CssFontLanguageOverrideKind",
    "CssFontSourceKind",
    "CssFontStyleKind",
    "CssFontVariantAlternatesValueKind",
    "CssFontVariantEastAsianValueKind",
    "CssFontVariantLigaturesValueKind",
    "CssFontVariantNumericValueKind",
    "CssHashType",
    "CssMediaFeature",
    "CssMediaFeatureComparison",
    "CssMediaFeatureNameKind",
    "CssMediaFeatureSyntaxKind",
    "CssMediaFeatureValue",
    "CssMediaFeatureValueKind",
    "CssMediaFeatureValueSyntaxKind",
    "CssMediaQuery",
    "CssNonnegativeIntegerSymbolPairOrder",
    "CssNumberType",
    "CssOpenTypeSettingsKind",
    "CssOpenTypeTaggedValueKind",
    "CssPagePseudoClassKind",
    "CssPageSelector",
    "CssPageSizeDescriptorKind",
    "CssPaintOrderKeyword",
    "CssPaintOrderValue",
    "CssPaintOrderValueKind",
    "CssParsedColorKind",
    "CssPositionAnchorValueKind",
    "CssPositionTryOrderValue",
    "CssPositionVisibilityValue",
    "CssPositionVisibilityValueKind",
    "CssPrimitiveValueKind",
    "CssPrimitiveValueOptions",
    "CssPrimitiveValueType",
    "CssQuotesValueKind",
    "CssRuleContext",
    "CssRuleEvent",
    "CssRuleEventKind",
    "CssScrollFunctionAxisKind",
    "CssScrollFunctionScrollerKind",
    "CssScrollFunctionValueKind",
    "CssScrollbarGutterValueKind",
    "CssStyleValueKind",
    "CssSupportsFeatureKind",
    "CssTextUnderlinePositionHorizontal",
    "CssTextUnderlinePositionValue",
    "CssTextUnderlinePositionVertical",
    "CssTextWrapModeValue",
    "CssTextWrapStyleValue",
    "CssTextWrapValue",
    "CssTextWrapValueKind",
    "CssTimelineNameItemKind",
    "CssTimelineNameValueKind",
    "CssTimelineScopeValueKind",
    "CssToken",
    "CssTokenType",
    "CssTouchActionKeyword",
    "CssTouchActionValue",
    "CssTouchActionValueKind",
    "CssTransitionBehaviorItemKind",
    "CssTransitionPropertyValueKind",
    "CssValueTypeSyntaxKind",
    "CssViewFunctionInsetKind",
    "CssViewFunctionInsetPosition",
    "CssViewFunctionValueKind",
    "CssViewTimelineInsetValueKind",
    "CssViewTransitionNameValueKind",
    "CssWhiteSpaceTrimValue",
    "CssWhiteSpaceTrimValueKind",
    "CssWillChangeFeatureKind",
    "CssWillChangeValueKind",
]

[export.mangle]
rename_types = "PascalCase"
