language = "C++"
header = """/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */"""
pragma_once = true
include_version = true
namespaces = ["Web", "CSS", "Parser", "FFI"]
line_length  = 120
tab_width = 4
no_includes = true
sys_includes = ["stdint.h", "stddef.h"]
usize_is_size_t = true

[parse]
parse_deps = false

[parse.expand]
all_features = false

[export]
include = ["CssAnchorNameOrScopeValueKind", "CssBooleanExpressionEventKind", "CssColorSchemeValue", "CssColorSchemeValueKind", "CssComponentValue", "CssComponentValueKind", "CssContainValue", "CssContainValueKind", "CssContainerTypeValueKind", "CssCounterStyleKind", "CssCounterStyleNegativeSymbolCount", "CssCounterStyleRangeKind", "CssCounterStyleSymbolsType", "CssCounterStyleSystemKind", "CssCropOrCrossKind", "CssDeclaration", "CssHashType", "CssMediaFeature", "CssMediaFeatureComparison", "CssMediaFeatureNameKind", "CssMediaFeatureSyntaxKind", "CssMediaFeatureValue", "CssMediaFeatureValueKind", "CssMediaQuery", "CssNonnegativeIntegerSymbolPairOrder", "CssNumberType", "CssPaintOrderKeyword", "CssPaintOrderValue", "CssPaintOrderValueKind", "CssPositionAnchorValueKind", "CssPositionVisibilityValue", "CssPositionVisibilityValueKind", "CssQuotesValueKind", "CssRuleContext", "CssRuleEvent", "CssRuleEventKind", "CssScrollbarGutterValueKind", "CssSupportsFeatureKind", "CssTextUnderlinePositionHorizontal", "CssTextUnderlinePositionValue", "CssTextUnderlinePositionVertical", "CssTimelineScopeValueKind", "CssToken", "CssTokenType", "CssTouchActionKeyword", "CssTouchActionValue", "CssTouchActionValueKind", "CssValueTypeSyntaxKind", "CssWhiteSpaceTrimValue", "CssWhiteSpaceTrimValueKind", "CssWillChangeFeatureKind", "CssWillChangeValueKind"]

[export.mangle]
rename_types = "PascalCase"
